spring:
  jpa:
    hibernate:
      ddt-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/aula_kotlin?createDatabaseIfNotExist=true
    username: root
    password: admin
  jackson:
    default-property-inclusion: nun_null